export const mock_permissions = [
    {
        id: '482519172976709',
        parent: null,
        children: [],
        depth: 0,
        name: '个人主页',
        label: 'sys.menu2.home.index',
        resourceType: '20',
        treeGrade: null,
        describe: '',
        isGeneral: false,
        path: 'home',
        component: '/home/index.tsx',
        state: true,
        sortValue: 1,
        icon: 'ic2-home',
        group: null,
        dataScope: null,
        customClass: null,
        isDef: false,
        parentId: null,
        readonly: false,
        deletedAt: null,
        createdBy: null,
        createdAt: '2023-09-25T10:55:32.000Z',
        updatedBy: null,
        updatedAt: '2023-09-25T10:55:32.000Z',
    },
    {
        id: '473632799518789',
        parent: null,
        children: [
            {
                id: '473633613013061',
                parent: {
                    id: '473632799518789',
                    depth: 0,
                    name: '组织机构',
                    label: 'sys.menu2.org.index',
                    resourceType: '10',
                    treeGrade: null,
                    describe: '',
                    isGeneral: false,
                    path: 'org',
                    component: '',
                    state: true,
                    sortValue: 2,
                    icon: 'ic2-org',
                    group: '',
                    dataScope: null,
                    customClass: null,
                    isDef: false,
                    parentId: null,
                    readonly: false,
                    deletedAt: null,
                    createdBy: null,
                    createdAt: '2023-08-31T08:16:48.000Z',
                    updatedBy: null,
                    updatedAt: '2023-08-31T08:16:48.000Z',
                },
                children: [],
                depth: 0,
                name: '机构管理',
                label: 'sys.menu2.org.org',
                resourceType: '20',
                treeGrade: null,
                describe: '',
                isGeneral: false,
                path: 'orgs',
                component: '/org/orgs/list.tsx',
                state: true,
                sortValue: 1,
                icon: '',
                group: '',
                dataScope: null,
                customClass: null,
                isDef: false,
                parentId: '473632799518789',
                readonly: false,
                deletedAt: null,
                createdBy: null,
                createdAt: '2023-08-31T08:20:06.000Z',
                updatedBy: null,
                updatedAt: '2023-08-31T08:20:06.000Z',
            },
            // {
            //     id: '473633775972421',
            //     parent: {
            //         id: '473632799518789',
            //         depth: 0,
            //         name: '组织机构',
            //         label: 'sys.menu2.org.index',
            //         resourceType: '10',
            //         treeGrade: null,
            //         describe: '',
            //         isGeneral: false,
            //         path: 'org',
            //         component: '',
            //         state: true,
            //         sortValue: 2,
            //         icon: 'ic2-org',
            //         group: '',
            //         dataScope: null,
            //         customClass: null,
            //         isDef: false,
            //         parentId: null,
            //         readonly: false,
            //         deletedAt: null,
            //         createdBy: null,
            //         createdAt: '2023-08-31T08:16:48.000Z',
            //         updatedBy: null,
            //         updatedAt: '2023-08-31T08:16:48.000Z',
            //     },
            //     children: [],
            //     depth: 0,
            //     name: '岗位管理',
            //     label: 'sys.menu2.org.station',
            //     resourceType: '20',
            //     treeGrade: null,
            //     describe: '',
            //     isGeneral: false,
            //     path: 'stations',
            //     component: '/org/stations/list.page.tsx',
            //     state: true,
            //     sortValue: 2,
            //     icon: '',
            //     group: '',
            //     dataScope: null,
            //     customClass: null,
            //     isDef: false,
            //     parentId: '473632799518789',
            //     readonly: false,
            //     deletedAt: null,
            //     createdBy: null,
            //     createdAt: '2023-08-31T08:20:46.000Z',
            //     updatedBy: null,
            //     updatedAt: '2023-08-31T08:20:46.000Z',
            // },
            {
                id: '473633960718405',
                parent: {
                    id: '473632799518789',
                    depth: 0,
                    name: '组织机构',
                    label: 'sys.menu2.org.index',
                    resourceType: '10',
                    treeGrade: null,
                    describe: '',
                    isGeneral: false,
                    path: 'org',
                    component: '',
                    state: true,
                    sortValue: 2,
                    icon: 'ic2-org',
                    group: '',
                    dataScope: null,
                    customClass: null,
                    isDef: false,
                    parentId: null,
                    readonly: false,
                    deletedAt: null,
                    createdBy: null,
                    createdAt: '2023-08-31T08:16:48.000Z',
                    updatedBy: null,
                    updatedAt: '2023-08-31T08:16:48.000Z',
                },
                children: [],
                depth: 0,
                name: '用户管理',
                label: 'sys.menu2.org.user',
                resourceType: '20',
                treeGrade: null,
                describe: '',
                isGeneral: false,
                path: 'users',
                component: '/org/users/list.tsx',
                state: true,
                sortValue: 3,
                icon: '',
                group: '',
                dataScope: null,
                customClass: null,
                isDef: false,
                parentId: '473632799518789',
                readonly: false,
                deletedAt: null,
                createdBy: null,
                createdAt: '2023-08-31T08:21:31.000Z',
                updatedBy: null,
                updatedAt: '2023-08-31T08:21:31.000Z',
            },
        ],
        depth: 0,
        name: '组织机构',
        label: 'sys.menu2.org.index',
        resourceType: '10',
        treeGrade: null,
        describe: '',
        isGeneral: false,
        path: 'org',
        component: '',
        state: true,
        sortValue: 2,
        icon: 'ic2-org',
        group: '',
        dataScope: null,
        customClass: null,
        isDef: false,
        parentId: null,
        readonly: false,
        deletedAt: null,
        createdBy: null,
        createdAt: '2023-08-31T08:16:48.000Z',
        updatedBy: null,
        updatedAt: '2023-08-31T08:16:48.000Z',
    },
    // {
    //     id: '477503721513029',
    //     parent: null,
    //     children: [
    //         {
    //             id: '477506197712965',
    //             parent: {
    //                 id: '477503721513029',
    //                 depth: 0,
    //                 name: '系统设置',
    //                 label: 'sys.menu2.setting.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'setting',
    //                 component: '',
    //                 state: true,
    //                 sortValue: 3,
    //                 icon: 'ic2-setting',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-09-11T06:47:37.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-09-11T06:47:37.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '菜单管理',
    //             label: 'sys.menu2.setting.menu',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'menus',
    //             component: '/setting/menus/list.page.tsx',
    //             state: true,
    //             sortValue: 1,
    //             icon: null,
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '477503721513029',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-09-11T06:57:42.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-09-11T06:57:42.000Z',
    //         },
    //         {
    //             id: '477506457538629',
    //             parent: {
    //                 id: '477503721513029',
    //                 depth: 0,
    //                 name: '系统设置',
    //                 label: 'sys.menu2.setting.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'setting',
    //                 component: '',
    //                 state: true,
    //                 sortValue: 3,
    //                 icon: 'ic2-setting',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-09-11T06:47:37.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-09-11T06:47:37.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '字典管理',
    //             label: 'sys.menu2.setting.dictionary',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'dictionaries',
    //             component: '/setting/dictionaries/list.page.tsx',
    //             state: true,
    //             sortValue: 2,
    //             icon: null,
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '477503721513029',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-09-11T06:58:45.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-09-11T06:58:45.000Z',
    //         },
    //         {
    //             id: '477506718847045',
    //             parent: {
    //                 id: '477503721513029',
    //                 depth: 0,
    //                 name: '系统设置',
    //                 label: 'sys.menu2.setting.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'setting',
    //                 component: '',
    //                 state: true,
    //                 sortValue: 3,
    //                 icon: 'ic2-setting',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-09-11T06:47:37.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-09-11T06:47:37.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '参数管理',
    //             label: 'sys.menu2.setting.parameter',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'parameters',
    //             component: '/setting/parameters/list.page.tsx',
    //             state: true,
    //             sortValue: 3,
    //             icon: null,
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '477503721513029',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-09-11T06:59:49.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-09-11T06:59:49.000Z',
    //         },
    //     ],
    //     depth: 0,
    //     name: '系统设置',
    //     label: 'sys.menu2.setting.index',
    //     resourceType: '10',
    //     treeGrade: null,
    //     describe: null,
    //     isGeneral: false,
    //     path: 'setting',
    //     component: '',
    //     state: true,
    //     sortValue: 3,
    //     icon: 'ic2-setting',
    //     group: null,
    //     dataScope: null,
    //     customClass: null,
    //     isDef: false,
    //     parentId: null,
    //     readonly: false,
    //     deletedAt: null,
    //     createdBy: null,
    //     createdAt: '2023-09-11T06:47:37.000Z',
    //     updatedBy: null,
    //     updatedAt: '2023-09-11T06:47:37.000Z',
    // },
    // {
    //     id: '512095515308101',
    //     parent: null,
    //     children: [
    //         {
    //             id: '477506352619589',
    //             parent: {
    //                 id: '512095515308101',
    //                 depth: 0,
    //                 name: '权限管理',
    //                 label: 'sys.menu2.authority.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'authority',
    //                 component: null,
    //                 state: true,
    //                 sortValue: 4,
    //                 icon: 'ic2-authority',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-12-18T00:41:59.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-12-18T00:41:59.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '角色管理',
    //             label: 'sys.menu2.authority.role',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'roles',
    //             component: '/authority/roles/list.page.tsx',
    //             state: true,
    //             sortValue: 1,
    //             icon: null,
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '512095515308101',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-09-11T06:58:19.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-09-11T06:58:19.000Z',
    //         },
    //     ],
    //     depth: 0,
    //     name: '权限管理',
    //     label: 'sys.menu2.authority.index',
    //     resourceType: '10',
    //     treeGrade: null,
    //     describe: null,
    //     isGeneral: false,
    //     path: 'authority',
    //     component: null,
    //     state: true,
    //     sortValue: 4,
    //     icon: 'ic2-authority',
    //     group: null,
    //     dataScope: null,
    //     customClass: null,
    //     isDef: false,
    //     parentId: null,
    //     readonly: false,
    //     deletedAt: null,
    //     createdBy: null,
    //     createdAt: '2023-12-18T00:41:59.000Z',
    //     updatedBy: null,
    //     updatedAt: '2023-12-18T00:41:59.000Z',
    // },
    // {
    //     id: '512103019884613',
    //     parent: null,
    //     children: [
    //         {
    //             id: '477506603237445',
    //             parent: {
    //                 id: '512103019884613',
    //                 depth: 0,
    //                 name: '基础配置',
    //                 label: 'sys.menu2.base.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'base',
    //                 component: null,
    //                 state: true,
    //                 sortValue: 5,
    //                 icon: 'ic2-base',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-12-18T01:12:31.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-12-18T01:12:31.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '行政区划',
    //             label: 'sys.menu2.base.area',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'areas',
    //             component: '/base/areas/list.page.tsx',
    //             state: true,
    //             sortValue: 1,
    //             icon: null,
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '512103019884613',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-09-11T06:59:21.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-09-11T06:59:21.000Z',
    //         },
    //     ],
    //     depth: 0,
    //     name: '基础配置',
    //     label: 'sys.menu2.base.index',
    //     resourceType: '10',
    //     treeGrade: null,
    //     describe: null,
    //     isGeneral: false,
    //     path: 'base',
    //     component: null,
    //     state: true,
    //     sortValue: 5,
    //     icon: 'ic2-base',
    //     group: null,
    //     dataScope: null,
    //     customClass: null,
    //     isDef: false,
    //     parentId: null,
    //     readonly: false,
    //     deletedAt: null,
    //     createdBy: null,
    //     createdAt: '2023-12-18T01:12:31.000Z',
    //     updatedBy: null,
    //     updatedAt: '2023-12-18T01:12:31.000Z',
    // },
    // {
    //     id: '512216121036869',
    //     parent: null,
    //     children: [
    //         {
    //             id: '512216970563653',
    //             parent: {
    //                 id: '512216121036869',
    //                 depth: 0,
    //                 name: '资源管理',
    //                 label: 'sys.menu2.resource.index',
    //                 resourceType: '10',
    //                 treeGrade: null,
    //                 describe: null,
    //                 isGeneral: false,
    //                 path: 'resource',
    //                 component: null,
    //                 state: true,
    //                 sortValue: 6,
    //                 icon: 'ic2-resource',
    //                 group: null,
    //                 dataScope: null,
    //                 customClass: null,
    //                 isDef: false,
    //                 parentId: null,
    //                 readonly: false,
    //                 deletedAt: null,
    //                 createdBy: null,
    //                 createdAt: '2023-12-18T08:52:44.000Z',
    //                 updatedBy: null,
    //                 updatedAt: '2023-12-18T08:52:44.000Z',
    //             },
    //             children: [],
    //             depth: 0,
    //             name: '对象存储',
    //             label: 'sys.menu2.resource.oss',
    //             resourceType: '20',
    //             treeGrade: null,
    //             describe: null,
    //             isGeneral: false,
    //             path: 'osses',
    //             component: '/resource/osses/list.page.tsx',
    //             state: true,
    //             sortValue: 1,
    //             icon: '',
    //             group: null,
    //             dataScope: null,
    //             customClass: null,
    //             isDef: false,
    //             parentId: '512216121036869',
    //             readonly: false,
    //             deletedAt: null,
    //             createdBy: null,
    //             createdAt: '2023-12-18T08:56:11.000Z',
    //             updatedBy: null,
    //             updatedAt: '2023-12-18T08:56:11.000Z',
    //         },
    //     ],
    //     depth: 0,
    //     name: '资源管理',
    //     label: 'sys.menu2.resource.index',
    //     resourceType: '10',
    //     treeGrade: null,
    //     describe: null,
    //     isGeneral: false,
    //     path: 'resource',
    //     component: null,
    //     state: true,
    //     sortValue: 6,
    //     icon: 'ic2-resource',
    //     group: null,
    //     dataScope: null,
    //     customClass: null,
    //     isDef: false,
    //     parentId: null,
    //     readonly: false,
    //     deletedAt: null,
    //     createdBy: null,
    //     createdAt: '2023-12-18T08:52:44.000Z',
    //     updatedBy: null,
    //     updatedAt: '2023-12-18T08:52:44.000Z',
    // },
];
